### ISSUE TITLE
error when node db/seed.js --flush 

### ISSUE THREAD

**Issue by gengzhichen** [substance/substance-legacy#207]
version substance-substance-v0.3.6-323-g57ad930
node js 0.6.8

When I run  node db/seed.js --flush 
it shows:

module.js:337
    throw new Error("Cannot find module '" + request + "'");
          ^
Error: Cannot find module '../lib/data/data'
    at Function._resolveFilename (module.js:337:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)
    at Object.<anonymous> (/usr/local/substance-substance-57ad930/db/seed.js:3:12)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Array.0 (module.js:484:10)

**Comment by michael** [comment]
Have you initialized the submodules?

git submodule init
git submodule updates

**Comment by gengzhichen** [comment]
my fault. sorry for disturbing you.
