### ISSUE TITLE
error on running cake couch:push

### ISSUE THREAD

**Issue by gengzhichen** [substance/substance-legacy#208]
node v0.6.8
coffee-script 1.3.3

Can you help
I got his error when I running 

cake couch:push

/usr/local/lib/coffee-script/lib/coffee-script/coffee-script.js:51
      throw err;
            ^
SyntaxError: In Cakefile, octal escape sequences '\033[0;31m' are not allowed on line 13
    at SyntaxError (unknown source)
    at Lexer.error (/usr/local/lib/coffee-script/lib/coffee-script/lexer.js:682:13)
    at Lexer.stringToken (/usr/local/lib/coffee-script/lib/coffee-script/lexer.js:170:14)
    at Lexer.tokenize (/usr/local/lib/coffee-script/lib/coffee-script/lexer.js:33:137)
    at /usr/local/lib/coffee-script/lib/coffee-script/coffee-script.js:43:32
    at Object.run (/usr/local/lib/coffee-script/lib/coffee-script/coffee-script.js:79:34)
    at Object.run (/usr/local/lib/coffee-script/lib/coffee-script/cake.js:51:18)
    at Object.<anonymous> (/usr/local/lib/coffee-script/bin/cake:7:38)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)

**Comment by ceimedia** [comment]
Same error for me on windows...

**Comment by ceimedia** [comment]
What does cak:push do ? 
I get the same error message on 2 plateforms : windows an unbunto...

**Comment by kasperisager** [comment]
Exact same error here

Edit: Emptying the ANSI Terminal Color values did the trick for me

**Comment by mystoo** [comment]
Into Cakefile try this:

#ANSI terminal colors.
#red   = '\033[0;31m'
red   = '\x33[0;31m'
#green = '\033[0;32m'
green = '\x33[0;32m'
#reset = '\033[0m'
reset = '\x33[0m'

**Comment by michael** [comment]
We'll no longer address issues related to the 0.4.0 series. We're pushing hard on 0.5.0 featuring an all-new architecture.

Track progress here: https://github.com/substance/substance/tree/0.5.0
