### ISSUE TITLE
Missing module during startup

### ISSUE THREAD

**Issue by lilienthal** [substance/substance-legacy#212]
I've installed substance and I'm trying to start the server but it complains about a missing module:

[Error: Cannot find module '../build/Release/nodeproxy.node']
Error: Cannot find module '../build/Release/nodeproxy.node'
    at Function._resolveFilename (module.js:337:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)
    at Object.<anonymous> (/root/substance/node_modules/now/node_modules/node-proxy/lib/node-proxy.js:1:90)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Module.require (module.js:359:17)

I've successfully completed all the steps from the substance-internals document and have no idea what could be missing here.

**Comment by lilienthal** [comment]
There was a

npm install node-proxy

in directory node-modules/now missing!
