### ISSUE TITLE
When viewed with certain browsers (e.g. qt+webkit+javascript core) the server crashes

### ISSUE THREAD

**Issue by michael** [substance/substance-legacy#23]
Needs investigation. 

```
/home/saleshub/local/lib/node/.npm/dnode/0.3.9/package/lib/stream_socketio.js:5
    this.remoteAddress = client.request.socket.remoteAddress;
                                       ^
TypeError: Cannot read property 'socket' of null
    at EventEmitter.StreamIO (/home/saleshub/local/lib/node/.npm/dnode/0.3.9/package/lib/stream_socketio.js:5:40)
    at [object Object].<anonymous> (/home/saleshub/local/lib/node/.npm/dnode/0.3.9/package/lib/stream_socketio.js:32:23)
    at [object Object].emit (events.js:27:15)
    at [object Object]._onClientConnect (/home/saleshub/local/lib/node/.npm/socket.io/0.6.1/package/lib/socket.io/listener.js:150:8)
```

**Comment by michael** [comment]
Already fixed.
