### ISSUE TITLE
Error on local install

### ISSUE THREAD

**Issue by zachcp** [substance/substance-legacy#329]
Hi Substance,

I just learned of your existence and think this is a fantastic idea. As per the instructions in the Sandbox I tried to clone this to get it up and running and ran into the following error:

```
$ git clone https://github.com/substance/substance
$ cd substance
$ npm install
<wait while intalling deps>
$ npm start


module.js:340
    throw err;
          ^
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/zachpowers/Documents/git/substance/server.js:2:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
npm ERR! weird error 8
npm ERR! not ok code 0
---------------------------
```

any ideas on how to address this?

thanks,
zach cp

**Comment by andreypopp** [comment]
Hi, see the https://github.com/substance/screwdriver project. There are installation instructions in the README, they work just fine for me.

**Comment by zachcp** [comment]
Thanks @andreypopp  - that did the trick.  Is it worth directing other users to this page by incorporating that into the install instructions on http://sandbox.substance.io/ ?

**Comment by michael** [comment]
No longer applicable.
