### ISSUE TITLE
Issue with substance --package

### ISSUE THREAD

**Issue by michael** [substance/substance-legacy#332]
Tried to exec `substance --package` in the reader repo. Got this error:

```
dubmac:reader michael$ substance --package
{'git': False, 'package': None, 'argv': [], 'bundle': False, 'branch': None, 'action': None}
Replacing dependency: underscore = 1.5.x
Replacing dependency: substance-regexp = git+https://github.com/substance/regexp.git#0.1.x
Writing /Users/michael/reader/node_modules/substance-application/package.json
Replacing dependency: underscore = 1.5.x
Replacing dependency: substance-util = git+https://github.com/substance/util.git#0.2.x
Replacing dependency: substance-operator = git+https://github.com/substance/operator.git#0.2.x
Traceback (most recent call last):
  File "/usr/local/bin/substance", line 59, in <module>
    method(args)
  File "/Library/Python/2.7/site-packages/substance/screwdriver.py", line 129, in package
    create_package(folder, conf, table, tag)
  File "/Library/Python/2.7/site-packages/substance/version.py", line 141, in create_package
    replace_deps(config, table, "dependencies", tag, github)
  File "/Library/Python/2.7/site-packages/substance/version.py", line 134, in replace_deps
    raise RuntimeError("Incomplete specification %s in %s"%(dep, config["name"]));
RuntimeError: Incomplete specification substance-store in substance-chronicle
```

**Comment by obuchtala** [comment]
That happens when there is an incomplete specification of a dependency, as you find in all of our module.json files,
and there is no specification in project.json (in the mothership).
There are two ways to have such a module specification:
1. a (sub-)module
2. an entry in the `node_modules` section

The above error shows you exactly what is missing, i.e., there is a (incompletely specified) dependency in `substance-chronicle/module.json` to `substance-store`, which is not addressed in the `project.json` of `reader`.
