### ISSUE TITLE
Cannot call method 'replace' of undefined

### ISSUE THREAD

**Issue by luissquall** [substance/substance-legacy#70]
When I start the server, I get the following error:

TypeError: Cannot call method 'replace' of undefined
    at Function.escapeHTML (/Users/luissquall/projects/substance/server.js:288:17)
    at clientConfig (/Users/luissquall/projects/substance/server.js:311:22)
    at Object.<anonymous> (/Users/luissquall/projects/substance/server.js:330:58)
    at param (/Users/luissquall/local/node/lib/node/.npm/connect/1.3.0/package/lib/middleware/router.js:148:21)
    at pass (/Users/luissquall/local/node/lib/node/.npm/connect/1.3.0/package/lib/middleware/router.js:164:10)
    at Object.router [as handle](/Users/luissquall/local/node/lib/node/.npm/connect/1.3.0/package/lib/middleware/router.js:170:6)
    at next (/Users/luissquall/local/node/lib/node/.npm/connect/1.3.0/package/lib/http.js:204:15)
    at /Users/luissquall/local/node/lib/node/.npm/connect/1.3.0/package/lib/middleware/session.js:296:9
    at /Users/luissquall/local/node/lib/node/.npm/connect/1.3.0/package/lib/middleware/session.js:311:9
    at Array.0 (/Users/luissquall/local/node/lib/node/.npm/connect/1.3.0/package/lib/middleware/session/memory.js:57:7)

I'm using node v0.5.0-pre

**Comment by michael** [comment]
Looks like the transloadit (image processing service) credentials are missing in your config.json file. It should read like:

```
{
  "couchdb_url": "http://localhost:8888/substance",
  "server_host": null,
  "server_port": 3003,
  "secret": "secret option string for session security",
  "transloadit": {
    "auth": {
      "key": "your_key"
    },
    "template_id": "your_template_id",
    "redirect_url": "http://substance.io"
  }
}
```

In order to use images, you'd need to create an account at transloadit.com and insert your credentials.
I'll update Substance in such a way, that image support is disabled if the transloadit-credentials are missing.

**Comment by luissquall** [comment]
Thank you michael, that solved the issue. I thought it was optional because transloadit conf. was not mentioned in the Substance Internals document.

**Comment by michael** [comment]
Good :)
Well, keeping the docs up to date sometimes fails. However I'm trying to have them valid at least on every major release. 0.2.0 is getting close btw ;)
